version: 2
jobs:

  build:
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    docker:
      - image: docker:18.01.0-ce-git
    steps:
      - run:
          name: Install parallel gzip
          command: |
            apk add --no-cache pigz 
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            # Build docker image
            e=1 && for i in {1..5}; do
              docker build \
                --rm=false \
                -t rwblair/webhook_test:latest . \
                && e=0 && break || sleep 15
            done && [ "$e" -eq "0" ]
      - run:
          name: Docker save
          no_output_timeout: 40m
          command: |
            mkdir -p /tmp/cache
            docker save ubuntu:xenial-20161213 rwblair/webhook_test:latest \
            | pigz -8 -p 3 > /tmp/cache/docker.tar.gz

      - persist_to_workspace:
          root: /tmp
          paths:
            - cache/docker.tar.gz
            - src/fmriprep

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
